/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChaleChaleIdRouteImport } from './routes/chale.$chaleId'
import { Route as AdminImagesRouteImport } from './routes/admin.images'

const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaleChaleIdRoute = ChaleChaleIdRouteImport.update({
  id: '/chale/$chaleId',
  path: '/chale/$chaleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImagesRoute = AdminImagesRouteImport.update({
  id: '/admin/images',
  path: '/admin/images',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/admin/images': typeof AdminImagesRoute
  '/chale/$chaleId': typeof ChaleChaleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/admin/images': typeof AdminImagesRoute
  '/chale/$chaleId': typeof ChaleChaleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/admin/images': typeof AdminImagesRoute
  '/chale/$chaleId': typeof ChaleChaleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/avaliacoes' | '/admin/images' | '/chale/$chaleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/avaliacoes' | '/admin/images' | '/chale/$chaleId'
  id: '__root__' | '/' | '/avaliacoes' | '/admin/images' | '/chale/$chaleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  AdminImagesRoute: typeof AdminImagesRoute
  ChaleChaleIdRoute: typeof ChaleChaleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chale/$chaleId': {
      id: '/chale/$chaleId'
      path: '/chale/$chaleId'
      fullPath: '/chale/$chaleId'
      preLoaderRoute: typeof ChaleChaleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/images': {
      id: '/admin/images'
      path: '/admin/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AdminImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  AdminImagesRoute: AdminImagesRoute,
  ChaleChaleIdRoute: ChaleChaleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
